### ISSUE TITLE
Course complete page not working

### ISSUE THREAD

**Issue by xadahiya** [OpenMined/courses-app#96]
## Description
A clear and concise description of the bug.
When I go to https://courses.openmined.org/courses/our-privacy-opportunity/complete after finishing the course the page says "Sorry, it looks like there was an error!".

## How to Reproduce
Finish the course and go to https://courses.openmined.org/courses/our-privacy-opportunity/complete

## Screenshots
![Screenshot_2021-01-29 Our Privacy Opportunity - Complete](https://user-images.githubusercontent.com/9114274/106235733-4a9a4880-6221-11eb-82f6-e91e701ac8e6.png)

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by tthoraldson** [comment]
I'm experiencing this error screen as well when I attempt to go to https://courses.openmined.org/courses/our-privacy-opportunity/complete 

- OS Windows 10 Version 10.0.18363
- Browsers: 
    - Edge Version 88.0.705.68
    -  Chrome Version 88.0.4324.150

**Comment by tcp** [comment]
Thanks for reporting this @tthoraldson and @xadahiya.

I'll see if we can fix this in the next 48 hours.

**Comment by tcp** [comment]
Took a bit more time than expected but the fix was merged in `dev` and should hit the courses shortly.

**Comment by IRailean** [comment]
This issue is still present for me.

Chrome Version: 89.0.4389.82

**Comment by tcp** [comment]
Hey @IRailean! Thanks for reporting. This has been fixed in dev and will hit production in the next update (mon or tue).

**Comment by IRailean** [comment]
Hi, @tcp  . Thank you!
